#pragma once

// C++ Standard Libraries
#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cassert>
#include <climits>
#include <cfloat>
#include <ctime>
#include <chrono>
#include <random>
#include <algorithm>
#include <utility>
#include <functional>
#include <numeric>
#include <iterator>
#include <bitset>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <list>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>
#include <tuple>
#include <array>
#include <memory>
#include <new>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <future>
#include <atomic>
#include <typeinfo>
#include <typeindex>
#include <locale>
#include <codecvt>
#include <regex>
#include <stdexcept>
#include <system_error>
#include <initializer_list>
#include <complex>
#include <valarray>
#include <limits>
#include <exception>

// Legacy C Libraries
#include <cctype>
#include <cstdint>
#include <cstddef>
#include <csignal>
#include <clocale>
#include <cerrno>